# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build-Deploy Demo.SportLeagueManager.Web
run-name: ${{ github.actor }} is learning GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore Demo.Net/Demo.Net.sln
      
    - name: Build
      run: dotnet build Demo.Net/Demo.Net.sln --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish Demo.Net/Demo.SportLeagueManager.Web/Demo.SportLeagueManager.Web.csproj --configuration Release --output ./publish

    - name: Copy files to server via SSH
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: "./publish/"
        target: "~/SportLeagueManagerWeb"
